import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowDown, ArrowRight, ArrowUpRight, Bath, BedDouble, Check, ChevronLeft, ChevronRight, Download, Expand, MapPin, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Disclosure, EnquiryForm, PriceEstimator } from '@/components/prestige-tools';
import { asset, brochures, collections, plans, specifications } from '@/lib/prestige-data';

export const Route = createFileRoute('/')({
 head:()=>({meta:[{title:'Prestige Golden Grove | Elevated Living in Tellapur, Hyderabad'},{name:'description',content:'Explore Prestige Golden Grove: 28.6 acres, ten towers and six residence collections in Tellapur, Hyderabad. View all 27 original floor plans, amenities and project information.'},{property:'og:title',content:'Prestige Golden Grove | Tellapur, Hyderabad'},{property:'og:description',content:'A new perspective on elevated living. Discover original project visuals, 27 residence layouts and thoughtfully planned amenities.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),
 component: Index,
});
const nav=[['Overview','overview'],['Residences','residences'],['Amenities','amenities'],['Floor Plans','floor-plans'],['Location','location'],['Offers','offers'],['Contact','contact']];
const gallery=[{image:asset('project-019.jpg'),title:'Architecture, elevated'},{image:asset('project-006.jpg'),title:'A graceful arrival'},{image:asset('project-014.jpg'),title:'Club Sapphire'},{image:asset('project-012.jpg'),title:'Landscapes for living'}];
const faqs=[['Which residence collections are available?','The brochure lists 2 BED Classic (2B2T), 3 BED Aspire (3B2T), 3 BED Premia (3B3T), 3 BED Ultima (3B3T + Study), 4 BED Supreme (4B4T) and 4 BED Ultima (4B4T + Staff). Sale areas range from 1,169 to 3,013 sq. ft. Current inventory and pricing require confirmation.'],['Can I explore the original floor plans?','Yes. The floor-plan explorer includes all 27 individual layouts from brochure pages 72–98. Filter by collection and enlarge any plan to read the original measurements, orientation and key plan. Sale area is not the same as carpet area.'],['What amenities are described in the brochure?','Club Sapphire focuses on sports and health; Club Emerald on social and recreation facilities. Outdoor amenities include sports courts, pools, a jogging track, cycling track, pet park and landscaped leisure spaces. Final delivery and access terms should be confirmed with the developer.'],['Where is Prestige Golden Grove located?','The project is in Tellapur, Hyderabad. The brochure includes a location map and advertised journey times to the ORR, the IT corridor, Lingampally MMTS and the airport. All times are estimates and vary with traffic.'],['How can I access the brochure?','The four original brochure parts are available to open or download in the Contact section. The form is a demonstration and does not send requests; please contact the developer or your consultant directly for current project information.'],['Is the advertised Pre-EMI offer guaranteed?','No. The supplied advertisement promotes a 20% customer payment and 80% loan structure with a three-year Pre-EMI claim. Lender eligibility, sanction, who pays which charges, validity dates and contractual terms must be independently confirmed. The advertisement states “till Nov 2029” and validity from 10 October to 31 December 2026; those dates do not establish a contractual guarantee.']];
type ViewerItem={image:string;title:string;description?:string};
function Brand(){return <Link to="/" hash="top" className="brand" aria-label="Prestige Golden Grove home"><img src={asset('brand-mark.png')} alt="Original Golden Grove emblem"/><div className="brand-type"><span>PRESTIGE</span><strong>GOLDEN GROVE</strong></div></Link>;}
function Jump({id,children,variant='gold'}:{id:string;children:React.ReactNode;variant?:'gold'|'glass'|'editorial'}){return <Button variant={variant} asChild><Link to="/" hash={id}>{children}</Link></Button>;}
function Heading({eyebrow,title,description}:{eyebrow:string;title:React.ReactNode;description?:string}){return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{description&&<p>{description}</p>}</div>;}
function Index(){
 const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);const [filter,setFilter]=useState('A');const [viewer,setViewer]=useState<{items:ViewerItem[];index:number}|null>(null);
 useEffect(()=>{const scroll=()=>setScrolled(window.scrollY>30);scroll();window.addEventListener('scroll',scroll,{passive:true});return()=>window.removeEventListener('scroll',scroll);},[]);
 useEffect(()=>{if(!menu)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[menu]);
 const open=(image:string,title:string,description?:string)=>setViewer({items:[{image,title,description}],index:0});
 const visible=plans.filter(p=>filter==='all'||p.category===filter);
 const current=viewer?.items[viewer.index];
 const showPlan=(p:typeof plans[number])=>{const collection=collections.find(c=>c.key===p.category);open(p.image,`${collection?.name} · TYPE–${p.id}`,`${p.area.toLocaleString('en-IN')} sq. ft. sale area · ${p.facing} facing · Original brochure page ${p.page}`);};
 return <div id="top">
  <header className={`site-header ${scrolled||menu?'scrolled':''}`}><div className="container-wide header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([name,id])=><Link to="/" hash={id} key={id}>{name}</Link>)}</nav><Jump id="contact">Enquire Now <ArrowUpRight/></Jump><Button className="mobile-toggle" variant="ghost" size="icon" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="mobile-nav" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div>{menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{nav.map(([name,id])=><Link key={id} to="/" hash={id} onClick={()=>setMenu(false)}>{name}</Link>)}</nav>}</header>
  <main>
   <section className="hero" aria-label="Prestige Golden Grove"><img className="hero-image" src={asset('project-021.jpg')} alt="Original architectural rendering of Prestige Golden Grove towers illuminated at dusk" fetchPriority="high"/><div className="container-wide hero-inner"><div className="eyebrow">Tellapur, Hyderabad</div><p className="hero-project">Prestige Golden Grove</p><h1>A New Perspective<br/>on <em>Elevated Living.</em></h1><p className="hero-description">Where nature finds its place, and life finds a new rhythm. Thoughtfully designed residences in the heart of Tellapur.</p><div className="hero-actions"><Jump id="residences">Explore Residences <ArrowUpRight/></Jump><Jump id="contact" variant="glass">Request Information <ArrowUpRight/></Jump></div></div><div className="container-wide hero-bottom"><Link to="/" hash="overview" className="scroll-cue">DISCOVER THE GROVE <ArrowDown size={17}/></Link><span className="hero-caption">Original project rendering. Artist’s impression.</span></div></section>
   <section className="stats-band" aria-label="Verified project facts"><div className="container-wide stats-grid">{[['28.6','Acres of thoughtful planning'],['10','Iconic residential towers'],['2, 3 & 4','Bedroom residences'],['27','Original unit layouts']].map(([value,label])=><div className="stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
   <section id="overview" className="section"><div className="container-wide overview-grid"><div className="overview-copy"><div className="eyebrow">The Golden Grove vision</div><h2>Rooted in nature.<br/><span className="italic">Designed for tomorrow.</span></h2><p>Spread across 28.6 acres, Prestige Golden Grove brings ten towers together around a vast central green space. A community imagined to celebrate Tellapur’s natural beauty.</p><p>Open landscapes, natural light and cross ventilation. Here, progress respects nature — and every day has room to breathe.</p><Jump id="master-plan" variant="editorial">Discover the Master Plan <ArrowUpRight/></Jump></div><div className="overview-image"><img src={asset('project-018.jpg')} alt="Original aerial rendering showing towers planned around the central landscape" loading="lazy"/><div className="image-seal"><strong>28.6</strong><span>ACRES<br/>One considered vision.</span></div></div></div></section>
   <section id="gallery" className="section gallery-section"><div className="container-wide"><Heading eyebrow="A glimpse of the extraordinary" title={<>Life, beautifully <span className="italic">framed.</span></>} description="Discover the architecture, green spaces and gathering places that shape the Golden Grove experience."/><div className="gallery-grid">{gallery.map((g,i)=><Button variant="image" key={g.title} onClick={()=>setViewer({items:gallery.map(g=>({...g,description:'Original supplied architectural rendering · Artist’s impression'})),index:i})} aria-label={`Enlarge ${g.title}`}><img src={g.image} alt={`Original project rendering: ${g.title}`} loading="lazy"/><span className="gallery-label">{g.title}<Expand size={14}/></span></Button>)}</div><p className="small-note gallery-footnote">All visuals are original supplied project renders or brochure illustrations, not completed-project photographs.</p></div></section>
   <section id="residences" className="section residences-section"><div className="container-wide"><Heading eyebrow="The residence collections" title={<>A home for every<br/><span className="italic">way of living.</span></>} description="Six thoughtfully considered collections. From intimate beginnings to expansive family living, find the space that feels like you."/><div className="residences-grid">{collections.map(c=>{const p=plans.find(p=>p.category===c.key);return <article className="residence-card" key={c.key}><div className="residence-image"><img src={p?.preview} alt={`Original ${c.name} floor-plan preview`} loading="lazy"/></div><div className="residence-body"><h3>{c.name}</h3><div className="residence-details"><span><BedDouble size={13}/>{c.beds} Bedrooms</span><span><Bath size={13}/>{c.baths} Bathrooms</span>{c.extra&&<span><Check size={12}/>{c.extra}</span>}</div><p>{c.description}</p><div className="residence-bottom"><strong>{c.range}<small>SQ. FT. SALE AREA</small></strong><Button variant="editorial" asChild onClick={()=>setFilter(c.key)}><Link to="/" hash="floor-plans">View Floor Plans <ArrowUpRight/></Link></Button></div></div></article>;})}</div></div></section>
   <section id="floor-plans" className="section"><div className="container-wide"><Heading eyebrow="The floor-plan explorer" title={<>Considered spaces.<br/><span className="italic">Endless possibilities.</span></>} description="Explore all 27 original layouts. Enlarge a plan to inspect the official room dimensions, area breakdown and orientation."/><div className="filters" aria-label="Residence collection filters"><Button variant="filter" aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>All layouts</Button>{collections.map(c=><Button variant="filter" key={c.key} aria-pressed={filter===c.key} onClick={()=>setFilter(c.key)}>{c.name}</Button>)}</div><p className="plan-count" aria-live="polite">{visible.length} layouts · Areas shown are brochure sale areas, not carpet areas</p><div className="plans-grid">{visible.map(p=><article className="plan-card" key={p.id}><Button variant="image" onClick={()=>showPlan(p)} aria-label={`Enlarge floor plan TYPE ${p.id}`}><img src={p.preview} alt={`Original TYPE ${p.id} floor plan, ${p.area} sq. ft., ${p.facing} facing`} loading="lazy"/><span className="expand-corner"><Expand size={14}/></span></Button><div className="plan-info"><div><h3>{collections.find(c=>c.key===p.category)?.name} · TYPE–{p.id}</h3><p>{p.facing} facing · Brochure p. {p.page}</p></div><strong>{p.area.toLocaleString('en-IN')}<small>SQ. FT.</small></strong></div></article>)}</div><p className="small-note gallery-footnote">The original enlarged sheets retain all supplied dimensions and area tables. Layouts, specifications and final sale documents should be confirmed with the developer.</p></div></section>
   <section id="amenities" className="section amenities-section"><div className="container-wide"><Heading eyebrow="More than a home" title={<>An extraordinary<br/><span className="italic">everyday.</span></>} description="Two distinctive clubhouses. Landscapes to unwind in. Spaces for movement, connection and the simple joy of living well."/><div className="amenity-visuals">{[{image:asset('project-012.jpg'),title:'Club Sapphire · Sports & Health'},{image:asset('project-014.jpg'),title:'Club Emerald · Social & Recreation'}].map(a=><Button variant="image" key={a.title} onClick={()=>open(a.image,a.title,'Original project rendering · Artist’s impression')} aria-label={`Enlarge ${a.title}`}><img src={a.image} alt={a.title} loading="lazy"/><span className="gallery-label">{a.title}<Expand size={15}/></span></Button>)}</div><div className="amenity-groups"><div><h3>Move & restore.</h3><p>Indoor swimming pool with jacuzzi · Gym & aerobics studios · Yoga & Pilates rooms · His & Her Spa · Badminton, pickleball & squash courts</p></div><div><h3>Gather & belong.</h3><p>Banquet hall · Mini theatre · Co-working space · Café · Guest rooms · Terrace BBQ deck · Library · Indoor games · Billiards & table tennis</p></div><div><h3>Explore & unwind.</h3><p>Olympic-size pool with kids pool · Family pool · Tennis & padel courts · Jogging & cycling tracks · Pet park · Sensory park · Party lawns · Amphitheatre</p></div></div></div></section>
   <section id="master-plan" className="section"><div className="container-wide master-layout"><Button variant="image" onClick={()=>open(asset('master.jpg'),'The original master plan','Brochure page 23 · Outdoor amenities and planned community layout')} aria-label="Enlarge original master plan"><img src={asset('master.jpg')} alt="Original master plan showing tower placement and 23 outdoor amenities" loading="lazy"/><span className="expand-corner"><Expand size={16}/></span></Button><div className="master-copy"><div className="eyebrow">The bigger picture</div><h2>Every detail.<br/><span className="italic">In harmony.</span></h2><p>Ten towers along the edges. A green heart at the centre. The original master plan brings homes, two clubhouses and outdoor recreation into one thoughtful composition.</p><Button variant="editorial" onClick={()=>open(asset('master.jpg'),'The original master plan','Brochure page 23 · Refer to final sanctioned plans for contractual details')}>View Master Plan <Expand/></Button></div></div></section>
   <section id="location" className="section location-section"><div className="container-wide"><Heading eyebrow="Tellapur, Hyderabad" title={<>Close to the city.<br/><span className="italic">Closer to calm.</span></>} description="A home connected to Hyderabad’s IT corridor, with schools, healthcare and everyday destinations identified in the brochure."/><div className="location-grid"><Button variant="image" className="location-map" onClick={()=>open(asset('location.jpg'),'Original brochure location map','Tellapur, Hyderabad · Illustrative map, not live navigation')} aria-label="Enlarge location map"><img src={asset('location.jpg')} alt="Original Prestige Golden Grove location map for Tellapur, Hyderabad" loading="lazy"/><span className="expand-corner"><Expand size={16}/></span></Button><div>{[['2–3','ORR Exit 2 & Exit 3'],['10–15','Financial District, Gachibowli & HITEC City'],['20','Lingampally MMTS'],['30–35','Rajiv Gandhi International Airport']].map(([time,destination])=><div className="journey" key={destination}><strong>{time} <small>min</small></strong><span>{destination}</span></div>)}<p className="small-note location-note">Advertised brochure journey times are estimates, not guarantees, and vary with traffic, route and destination.</p><div className="nearby"><div><strong>SCHOOLS</strong>Gaudium · DPS, Kollur · Birla Open Minds</div><div><strong>HEALTHCARE</strong>Citizens · AIG · Continental</div><div><strong>EDUCATION</strong>ISB · GITAM · University of Hyderabad</div><div><strong>RETAIL</strong>Inorbit Mall · Neo Mall · GSM Mall</div></div></div></div></div></section>
   <section id="specifications" className="section"><div className="container-wide specs-layout"><div><div className="eyebrow">Thoughtful by design</div><h2>Quality in<br/><span className="italic">every detail.</span></h2><p className="small-note gallery-footnote">Specifications transcribed from brochure page 99. Final finishes and provisions are subject to developer confirmation and sale documents.</p></div><div>{specifications.map(([title,text])=><Disclosure key={title} title={title} text={text}/>)}</div></div></section>
   <section id="offers" className="section offer-section"><div className="container-wide offer-grid"><Button variant="image" className="offer-image" aria-label="Enlarge supplied Pre-EMI advertisement" onClick={()=>open(asset('pre-emi-offer.jpeg'),'Supplied Pre-EMI advertisement','Promotional claims only · Verify terms directly with the developer and lender')}><img src={asset('pre-emi-offer.jpeg')} alt="Supplied consultant advertisement: 10% initially, another 10% at agreement within 45 days, 80% loan and three-year Pre-EMI promotion" loading="lazy"/></Button><div className="offer-copy"><div className="eyebrow">The advertised Pre-EMI plan</div><h2>A new beginning.<br/><span className="italic">A considered approach.</span></h2><p className="offer-intro">The supplied advertisement presents this payment structure:</p><div className="payment-timeline"><div className="payment-step"><strong>10%</strong><span>Customer pays initially</span></div><div className="payment-step"><strong>+10%</strong><span>Agreement within 45 days</span></div><div className="payment-step"><strong>80%</strong><span>Advertised loan portion</span></div></div><p className="offer-tag">Promotional claim: “No EMI for 3 years” / Pre-EMI paid by Prestige.</p><p className="small-note">The advertisement states “till Nov 2029” and validity from 10 October to 31 December 2026. It names Axis Bank, ICICI Bank and Bajaj; these are advertiser claims, not independently verified lender approvals.</p><p className="small-note gallery-footnote">Confirm lender eligibility, loan sanction, dates, offer validity, payment responsibility and contractual terms directly with the developer and relevant lender. No loan approval, savings or payment benefit is guaranteed.</p><div className="hero-actions"><Jump id="contact">Request Offer Details <ArrowUpRight/></Jump></div></div></div></section>
   <section id="estimator" className="section"><div className="container-wide estimator-grid"><div className="estimator-copy"><div className="eyebrow">Plan your possibilities</div><h2>Your space.<br/><span className="italic">Your assumptions.</span></h2><p>Explore an illustrative property value and payment split using an area and price assumption of your choice.</p><p>No official project price is provided here. For a current quotation and all applicable charges, please contact the developer or your consultant.</p></div><PriceEstimator/></div></section>
   <section id="faq" className="section faq-section"><div className="container-wide faq-grid"><div><div className="eyebrow">A little more clarity</div><h2>Good questions.<br/><span className="italic">Thoughtful answers.</span></h2></div><div>{faqs.map(([title,text])=><Disclosure key={title} title={title} text={text}/>)}</div></div></section>
   <section id="contact" className="section contact-section"><div className="container-wide contact-grid"><div className="contact-copy"><div className="eyebrow">Your next chapter</div><h2>Let’s find your<br/><span className="italic">place in the grove.</span></h2><p>Explore the original brochures, choose your preferred residence and prepare your enquiry. This preview does not send your details to a sales team.</p><div className="contact-location"><MapPin size={22}/><div>Prestige Golden Grove<br/><span className="small-note">Tellapur, Hyderabad</span></div></div><p className="brochure-label">Original project brochures</p><div className="brochure-links">{brochures.map(b=><a key={b.range} href={b.url} target="_blank" rel="noreferrer" aria-label={`Open original brochure pages ${b.range}`}><Download size={13}/>Pages {b.range}</a>)}</div><p className="small-note gallery-footnote">Developer / sales contact details are not established for this website. Please use your existing developer or consultant contact.</p></div><EnquiryForm/></div></section>
   <section className="final-banner"><img src={asset('project-008.jpg')} alt="Original evening rendering of the illuminated Golden Grove clubhouse" loading="lazy"/><div className="final-banner-content"><h2>Some places are lived in.<br/><span className="italic">Others are felt.</span></h2><Jump id="contact">Discover Your Golden Grove <ArrowUpRight/></Jump></div></section>
  </main>
  <footer><div className="container-wide"><div className="footer-top"><Brand/><nav className="footer-nav" aria-label="Footer navigation">{nav.map(([name,id])=><Link key={id} to="/" hash={id}>{name}</Link>)}</nav></div><p className="footer-disclaimer">This property information page is based on the supplied Prestige Golden Grove brochures and promotional material. Visuals are artist’s impressions and brochure illustrations. Areas are brochure sale areas; actual carpet areas and dimensions are shown on original plans. All project details, specifications, approvals, prices, availability, offer validity and contractual terms must be confirmed directly with the developer. Travel times are estimates. The calculator is illustrative and the enquiry form is a demonstration only. This website does not establish official developer affiliation.</p><div className="footer-bottom"><span>© 2026 Prestige Golden Grove · Information preview</span><Link to="/" hash="top">Back to top ↑</Link></div></div></footer>
  <div className="mobile-sticky-cta"><span>Prestige Golden Grove<br/>Tellapur, Hyderabad</span><Jump id="contact">Enquire Now <ArrowUpRight/></Jump></div>
  <Dialog.Root open={!!viewer} onOpenChange={value=>{if(!value)setViewer(null);}}><Dialog.Portal><Dialog.Overlay className="viewer-overlay"/><Dialog.Content className="viewer-content"><div className="viewer-header"><div><Dialog.Title className="viewer-title">{current?.title}</Dialog.Title><Dialog.Description className="viewer-description">{current?.description||'Original supplied project visual'}</Dialog.Description></div><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="Close image viewer"><X/></Button></Dialog.Close></div><div className="viewer-scroll">{current&&<img src={current.image} alt={current.title}/>}</div><div className="viewer-footer"><span>Original project material</span>{viewer&&viewer.items.length>1&&<div className="flex items-center gap-2"><Button variant="editorial" aria-label="Previous image" onClick={()=>setViewer({...viewer,index:(viewer.index-1+viewer.items.length)%viewer.items.length})}><ChevronLeft/></Button><span>{viewer.index+1} / {viewer.items.length}</span><Button variant="editorial" aria-label="Next image" onClick={()=>setViewer({...viewer,index:(viewer.index+1)%viewer.items.length})}><ChevronRight/></Button></div>}{current&&<a href={current.image} target="_blank" rel="noreferrer">Open full-resolution image <ArrowUpRight size={14}/></a>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
