import { useState, type FormEvent } from 'react';
import { z } from 'zod';
import { ArrowUpRight, CheckCircle2, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { collections } from '@/lib/prestige-data';

export function Disclosure({ title, text }: { title: string; text: string }) {
 return <details><summary>{title}<Plus aria-hidden="true" /></summary><p>{text}</p></details>;
}
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
export function PriceEstimator() {
 const [area, setArea] = useState(''); const [rate, setRate] = useState(''); const [down, setDown] = useState(20);
 const valid = Number(area) > 0 && Number(rate) > 0 && Number(area) <= 100000 && Number(rate) <= 1000000;
 const total = valid ? Number(area) * Number(rate) : 0;
 return <div className="calculator"><div className="calculator-fields"><label className="field">Apartment area (sq. ft.)<input type="number" min="1" max="100000" placeholder="Enter area" value={area} onChange={e=>setArea(e.target.value)} /></label><label className="field">Assumed price / sq. ft. (₹)<input type="number" min="1" max="1000000" placeholder="Enter your assumption" value={rate} onChange={e=>setRate(e.target.value)} /></label></div><label className="field down-field">Down payment — {down}%<input type="range" min="0" max="100" value={down} onChange={e=>setDown(Number(e.target.value))} /></label><div className="calculator-results" aria-live="polite"><div className="calc-total"><span>Illustrative property value</span><strong>{valid ? money(total) : '—'}</strong></div><div className="calc-splits"><div><span>Estimated down payment</span><strong>{valid ? money(total*down/100) : '—'}</strong></div><div><span>Estimated remaining balance</span><strong>{valid ? money(total*(1-down/100)) : '—'}</strong></div></div></div><p className="small-note">Illustrative only, not an official price or loan quote. Excludes taxes, registration, maintenance, additional charges and interest. Enter positive assumptions within the stated input limits.</p></div>;
}
const enquirySchema = z.object({ name: z.string().trim().min(2,'Please enter your full name.').max(100), phone: z.string().trim().regex(/^\+?[\d\s()-]{10,20}$/,'Please enter a valid phone number.').refine(v => v.replace(/\D/g,'').length >= 10 && v.replace(/\D/g,'').length <= 15,'Use 10–15 digits.'), email: z.string().trim().email('Please enter a valid email address.').max(255), configuration: z.enum(['A','B','C','D','E','F'],{errorMap:()=>({message:'Please choose a residence collection.'})}), message: z.string().trim().max(1000,'Please keep your message under 1,000 characters.') });
export function EnquiryForm() {
 const [errors,setErrors]=useState<Record<string,string>>({}); const [submitted,setSubmitted]=useState(false);
 function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault();const result=enquirySchema.safeParse(Object.fromEntries(new FormData(e.currentTarget))); if(!result.success){setErrors(Object.fromEntries(result.error.issues.map(i=>[String(i.path[0]),i.message])));setSubmitted(false);return;}setErrors({});setSubmitted(true); }
 const error=(name:string)=>errors[name] ? <span id={`${name}-error`} className="field-error">{errors[name]}</span>:null;
 return <form className="enquiry-form" onSubmit={submit} noValidate onChange={()=>submitted&&setSubmitted(false)}><label className="field">Full name *<input name="name" autoComplete="name" maxLength={100} placeholder="Your full name" required aria-invalid={!!errors.name} aria-describedby={errors.name?'name-error':undefined}/>{error('name')}</label><label className="field">Phone number *<input name="phone" type="tel" autoComplete="tel" maxLength={20} placeholder="Your phone number" required aria-invalid={!!errors.phone} aria-describedby={errors.phone?'phone-error':undefined}/>{error('phone')}</label><label className="field">Email address *<input name="email" type="email" autoComplete="email" maxLength={255} placeholder="you@example.com" required aria-invalid={!!errors.email} aria-describedby={errors.email?'email-error':undefined}/>{error('email')}</label><label className="field">Preferred residence *<select name="configuration" defaultValue="" required aria-invalid={!!errors.configuration} aria-describedby={errors.configuration?'configuration-error':undefined}><option value="" disabled>Select a collection</option>{collections.map(c=><option key={c.key} value={c.key}>{c.name}</option>)}</select>{error('configuration')}</label><label className="field full-field">Your message<textarea name="message" maxLength={1000} rows={3} placeholder="Tell us what you’re looking for" aria-invalid={!!errors.message}/>{error('message')}</label><p className="form-note full-field">This is a demonstration form. Your enquiry will not be sent to a sales team.</p><div className="full-field"><Button variant="gold" type="submit">Preview Enquiry <ArrowUpRight /></Button></div>{submitted&&<div role="status" className="form-confirmation full-field"><CheckCircle2 size={20}/><div><strong>Demo enquiry completed.</strong><br/>Your details passed validation, but have not been transmitted or saved. Contact the developer or your consultant directly to make an enquiry.</div></div>}</form>;
}
